### ISSUE TITLE
Game should start only if a valid word is provided.

### ISSUE THREAD

**Issue by dorumrr** [vladmrn/hangman#1]
Keep "Start Game" button disabled while a valid word wasn't provided.

Suggestions: 

- Ensure the word has at least 5 characters.

- Limit the word input to letters only [azAZ].

**Comment by vladmrn** [comment]
Thank you for your feedback @dorumrr. I have implemented these 2 conditions, please let me know if you think that there is something else I can improve.

**Comment by dorumrr** [comment]
> Thank you for your feedback @dorumrr. I have implemented these 2 conditions, please let me know if you think that there is something else I can improve.

Awesome!
